### ISSUE TITLE
Update to 2.0.8 version

### ISSUE THREAD

**Issue by KonStg** [hunter-packages/SDL2#5]
It has many useful improvements.

**Comment by ruslo** [comment]
There is no release tags in upstream mirror: https://github.com/spurious/SDL-mirror it's not clear what is the 2.0.8 commit exactly. Can you point to it?

**Comment by KonStg** [comment]
Sure, I think this is: https://github.com/spurious/SDL-mirror/tree/release-2.0.8

**Comment by ruslo** [comment]
Okay, I've created branch [hunter-2.0.8](https://github.com/hunter-packages/SDL2/tree/hunter-2.0.8) basing on `ef5bf55e8` commit. Feel free to send patches there from previous `hunter-2.0.7` branch:
* https://github.com/hunter-packages/SDL2/commits/hunter-2.0.7

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
