### ISSUE TITLE
Update to 2.0.9

### ISSUE THREAD

**Issue by NeroBurner** [hunter-packages/SDL2#6]
https://github.com/spurious/SDL-mirror/tree/release-2.0.9

since the Update Request of 2.0.8 https://github.com/hunter-packages/SDL2/issues/5 Version 2.0.9 was released. Could you also make a branch for this release

**Comment by ruslo** [comment]
Done: https://github.com/hunter-packages/SDL2/tree/hunter-2.0.9

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
